export const districtNeighborhoodNamesByDistrictName = [
  {
    "district": "Adalar",
    "neighborhoods": [
      "Burgazada",
      "Heybeliada",
      "Kınalıada",
      "Nizam"
    ]
  },
  {
    "district": "Arnavutköy",
    "neighborhoods": [
      "Adnan Menderes",
      "Anadolu",
      "Arnavutköy Merkez",
      "Atatürk",
      "Baklalı",
      "Balaban",
      "Boğazköy İstiklal",
      "Bolluca",
      "Boyalık",
      "Çilingir",
      "Deliklikaya",
      "Dursunköy",
      "Durusu",
      "Fatih",
      "Hacımaşlı",
      "Hadımköy",
      "Haraççı",
      "Hicret",
      "İmrahor",
      "İslambey",
      "Karaburun",
      "Karlıbayır",
      "Mareşal Fevzi Çakmak",
      "Mavigöl",
      "Mehmet Akif Ersoy",
      "Mustafa Kemal Paşa",
      "Nenehatun",
      "Ömerli",
      "Sazlıbosna",
      "Taşoluk",
      "Tayakadın",
      "Terkos",
      "Yassıören",
      "Yeniköy",
      "Yeşilbayır",
      "Yunus Emre"
    ]
  },
  {
    "district": "Ataşehir",
    "neighborhoods": [
      "Aşıkveysel",
      "Atatürk",
      "Barbaros",
      "Esatpaşa",
      "Ferhatpaşa",
      "Fetih",
      "İçerenköy",
      "İnönü",
      "Kayışdağı",
      "Küçükbakkalköy",
      "Mevlana",
      "Mimar Sinan",
      "Mustafa Kemal",
      "Örnek",
      "Yeni Çamlıca",
      "Yenisahra",
      "Yenişehir"
    ]
  },
  {
    "district": "Avcılar",
    "neighborhoods": [
      "Ambarlı",
      "Cihangir",
      "Denizköşkler",
      "Firuzköy",
      "Gümüşpala",
      "Merkez",
      "Mustafa Kemalpaşa",
      "Tahtakale",
      "Üniversite",
      "Yeşilkent"
    ]
  },
  {
    "district": "Bağcılar",
    "neighborhoods": [
      "100. Yıl",
      "15 Temmuz",
      "Bağlar",
      "Barbaros",
      "Çınar",
      "Demirkapı",
      "Fatih",
      "Fevzi Çakmak",
      "Göztepe",
      "Güneşli",
      "Hürriyet",
      "İnönü",
      "Kemalpaşa",
      "Kirazlı",
      "Mahmutbey",
      "Merkez",
      "Sancaktepe",
      "Yavuz Selim",
      "Yenigün",
      "Yenimahalle",
      "Yıldıztepe"
    ]
  },
  {
    "district": "Bahçelievler",
    "neighborhoods": [
      "Bahçelievler",
      "Cumhuriyet",
      "Çobançeşme",
      "Fevzi Çakmak",
      "Hürriyet",
      "Kocasinan Merkez",
      "Soğanlı",
      "Şirinevler",
      "Yenibosna Merkez",
      "Zafer"
    ]
  },
  {
    "district": "Bakırköy",
    "neighborhoods": [
      "Ataköy 1. Kısım",
      "Ataköy 2-5-6. Kısım",
      "Ataköy 3-4-11. Kısım",
      "Ataköy 7-8-9-10. Kısım",
      "Basınköy",
      "Cevizlik",
      "Kartaltepe",
      "Osmaniye",
      "Sakızağacı",
      "Şenlikköy",
      "Yenimahalle",
      "Yeşilköy",
      "Zuhuratbaba"
    ]
  },
  {
    "district": "Başakşehir",
    "neighborhoods": [
      "Bahçeşehir 1. Kısım",
      "Bahçeşehir 2. Kısım",
      "Başak",
      "Başakşehir",
      "Güvercintepe",
      "Kayabaşı",
      "Şahintepe",
      "Şamlar",
      "Ziya Gökalp"
    ]
  },
  {
    "district": "Bayrampaşa",
    "neighborhoods": [
      "Altıntepsi",
      "Cevatpaşa",
      "İsmet Paşa",
      "Kartaltepe",
      "Kocatepe",
      "Muratpaşa",
      "Orta",
      "Terazidere",
      "Vatan",
      "Yıldırım"
    ]
  },
  {
    "district": "Beşiktaş",
    "neighborhoods": [
      "Akat",
      "Arnavutköy",
      "Balmumcu",
      "Bebek",
      "Cihannüma",
      "Dikilitaş",
      "Etiler",
      "Gayrettepe",
      "Konaklar",
      "Kuruçeşme",
      "Kültür",
      "Levazım",
      "Levent",
      "Mecidiye",
      "Nisbetiye",
      "Ortaköy",
      "Sinanpaşa",
      "Türkali",
      "Ulus",
      "Vişnezade",
      "Yıldız"
    ]
  },
  {
    "district": "Beykoz",
    "neighborhoods": [
      "Acarlar",
      "Akbaba",
      "Alibahadır",
      "Anadolu Hisarı",
      "Anadolu Kavağı",
      "Anadolufeneri",
      "Baklacı",
      "Bozhane",
      "Cumhuriyet",
      "Çamlıbahçe",
      "Çengeldere",
      "Çiftlik",
      "Çubuklu",
      "Dereseki",
      "Elmalı",
      "Fatih",
      "Göksu",
      "Göllü",
      "Görele",
      "Göztepe",
      "Gümüşsuyu",
      "İncirköy",
      "İshaklı",
      "Kanlıca",
      "Kavacık",
      "Kaynarca",
      "Kılıçlı",
      "Mahmutşevketpaşa",
      "Merkez",
      "Öğümce",
      "Örnekköy",
      "Paşabahçe",
      "Paşamandıra",
      "Polonezköy",
      "Poyrazköy",
      "Riva",
      "Rüzgarlıbahçe",
      "Tokatköy",
      "Yalıköy",
      "Yavuz Selim",
      "Yeni Mahalle",
      "Zerzavatçı"
    ]
  },
  {
    "district": "Beylikdüzü",
    "neighborhoods": [
      "Adnan Kahveci",
      "Barış",
      "Büyükşehir",
      "Cumhuriyet",
      "Dereağzı",
      "Gürpınar",
      "Kavaklı",
      "Marmara",
      "Sahil",
      "Yakuplu"
    ]
  },
  {
    "district": "Beyoğlu",
    "neighborhoods": [
      "Arap Cami",
      "Asmalı Mescit",
      "Bedrettin",
      "Bereketzade",
      "Bostan",
      "Bülbül",
      "Camiikebir",
      "Cihangir",
      "Çatma Mescit",
      "Çukur",
      "Emekyemez",
      "Evliya Çelebi",
      "Fetihtepe",
      "Firuzağa",
      "Gümüşsuyu",
      "Hacıahmet",
      "Hacımimi",
      "Halıcıoğlu",
      "Hüseyinağa",
      "İstiklal",
      "Kadımehmet Efendi",
      "Kamer Hatun",
      "Kaptanpaşa",
      "Katipmustafa Çelebi",
      "Keçeci Piri",
      "Kılıçali Paşa",
      "Kocatepe",
      "Kulaksız",
      "Küçük Piyale",
      "Ömer Avni",
      "Örnektepe",
      "Piripaşa",
      "Piyalepaşa",
      "Sururi Mehmet Efendi",
      "Sütlüce",
      "Yahya Kahya",
      "Yenişehir"
    ]
  },
  {
    "district": "Büyükçekmece",
    "neighborhoods": [
      "19 Mayıs",
      "Ahmediye",
      "Alkent 2000",
      "Atatürk",
      "Bahçelievler",
      "Celaliye",
      "Cumhuriyet",
      "Çakmaklı",
      "Dizdariye",
      "Ekinoba",
      "Fatih",
      "Güzelce",
      "Kamiloba",
      "Karaağaç",
      "Kumburgaz",
      "Mimar Sinan",
      "Mimaroba",
      "Murat Çesme",
      "Pınartepe",
      "Sinanoba",
      "Türkoba",
      "Ulus",
      "Yenimahalle"
    ]
  },
  {
    "district": "Çatalca",
    "neighborhoods": [
      "Akalan",
      "Aydınlar",
      "Bahşayiş",
      "Başak",
      "Belgrat",
      "Celepköy",
      "Çakıl",
      "Çanakça",
      "Çiftlikköy",
      "Dağyenice",
      "Elbasan",
      "Fatih",
      "Gökçeali",
      "Gümüşpınar",
      "Hallaçlı",
      "Hisarbeyli",
      "İhsaniye",
      "İnceğiz",
      "İzzettin",
      "Kabakça",
      "Kaleiçi",
      "Kalfa",
      "Karacaköy Merkez",
      "Karamandere",
      "Kestanelik",
      "Kızılcaali",
      "Muratbey Merkez",
      "Nakkaş",
      "Oklalı",
      "Ormanlı",
      "Ovayenice",
      "Örcünlü",
      "Örencik",
      "Subaşı",
      "Yalıköy",
      "Yaylacık",
      "Yazlık"
    ]
  },
  {
    "district": "Çekmeköy",
    "neighborhoods": [
      "Alemdağ",
      "Aydınlar",
      "Cumhuriyet",
      "Çamlık",
      "Çatalmeşe",
      "Ekşioğlu",
      "Güngören",
      "Hamidiye",
      "Hüseyinli",
      "Kirazlıdere",
      "Koçullu",
      "Mehmet Akif",
      "Merkez",
      "Mimar Sinan",
      "Nişantepe",
      "Ömerli",
      "Reşadiye",
      "Sırapınar",
      "Soğukpınar",
      "Sultançiftliği",
      "Taşdelen"
    ]
  },
  {
    "district": "Esenler",
    "neighborhoods": [
      "15 Temmuz",
      "Birlik",
      "Çifte Havuzlar",
      "Fatih",
      "Fevzi Çakmak",
      "Havaalanı",
      "Kemer",
      "Menderes",
      "Mimar Sinan",
      "Nine Hatun",
      "Oruçreis",
      "Tuna",
      "Turgut Reis",
      "Yavuz Selim"
    ]
  },
  {
    "district": "Esenyurt",
    "neighborhoods": [
      "Akçaburgaz",
      "Akevler",
      "Akşemseddin",
      "Ardıçlı",
      "Aşık Veysel",
      "Atatürk",
      "Bağlarçeşme",
      "Balıkyolu",
      "Barbaros Hayrettin Paşa",
      "Battalgazi",
      "Cumhuriyet",
      "Çınar",
      "Fatih",
      "Gökevler",
      "Güzelyurt",
      "Hürriyet",
      "İncirtepe",
      "İnönü",
      "İstiklal",
      "Koza",
      "Mehmet Akif Ersoy",
      "Mehterçeşme",
      "Mevlana",
      "Necip Fazıl Kısakürek",
      "Orhan Gazi",
      "Osmangazi",
      "Pınar",
      "Piri Reis",
      "Saadetdere",
      "Selahaddin Eyyubi",
      "Sultaniye",
      "Süleymaniye",
      "Şehitler",
      "Turgut Özal",
      "Üçevler",
      "Yeşilkent",
      "Yunus Emre",
      "Zafer"
    ]
  },
  {
    "district": "Eyüpsultan",
    "neighborhoods": [
      "Ağaçlı",
      "Akpınar",
      "Akşemsettin",
      "Alibeyköy",
      "Çırçır",
      "Çiftalan",
      "Defterdar",
      "Emniyettepe",
      "Esentepe",
      "Göktürk Merkez",
      "Güzeltepe",
      "Işıklar",
      "İhsaniye",
      "İslambey",
      "Karadolap",
      "Merkez",
      "Mithatpaşa",
      "Nişancı",
      "Odayeri",
      "Pirinççi",
      "Rami Cuma",
      "Rami Yeni",
      "Sakarya",
      "Silahtarağa",
      "Topçular",
      "Yeşilpınar"
    ]
  },
  {
    "district": "Fatih",
    "neighborhoods": [
      "Aksaray",
      "Akşemsettin",
      "Alemdar",
      "Ali Kuşçu",
      "Atikali",
      "Ayvansaray",
      "Balat",
      "Beyazıt",
      "Binbirdirek",
      "Cankurtaran",
      "Cerrahpaşa",
      "Cibali",
      "Demirtaş",
      "Derviş Ali",
      "Hacı Kadın",
      "Haseki Sultan",
      "Hırka-i Şerif",
      "Hocapaşa",
      "İskenderpaşa",
      "Kalenderhane",
      "Karagümrük",
      "Katip Kasım",
      "Kemalpaşa",
      "Küçük Ayasofya",
      "Mercan",
      "Mevlanakapı",
      "Mimar Hayrettin",
      "Mimar Kemalettin",
      "Molla Gürani",
      "Molla Hüsrev",
      "Muhsine Hatun",
      "Nişanca",
      "Rüstempaşa",
      "Saraç İshak",
      "Seyyid Ömer",
      "Sultan Ahmet",
      "Sururi",
      "Süleymaniye",
      "Sümbül Efendi",
      "Şehremini",
      "Şehsuvar Bey",
      "Tahtakale",
      "Topkapı",
      "Yavuz Sinan",
      "Yavuz Sultan Selim",
      "Yedikule",
      "Zeyrek"
    ]
  },
  {
    "district": "Gaziosmanpaşa",
    "neighborhoods": [
      "Bağlarbaşı",
      "Barbaros Hayrettin Paşa",
      "Fevzi Çakmak",
      "Hürriyet",
      "Karadeniz",
      "Karayolları",
      "Karlıtepe",
      "Kazım Karabekir",
      "Merkez",
      "Mevlana",
      "Sarıgöl",
      "Şemsipaşa",
      "Yeni Mahalle",
      "Yenidoğan",
      "Yıldıztabya"
    ]
  },
  {
    "district": "Güngören",
    "neighborhoods": [
      "Abdurrahman Nafiz Gürman",
      "Akıncılar",
      "Gençosman",
      "Güneştepe",
      "Haznedar",
      "Mareşal Çakmak",
      "Mehmet Nesih Özmen",
      "Merkez",
      "Sanayi",
      "Tozkoparan"
    ]
  },
  {
    "district": "Kadıköy",
    "neighborhoods": [
      "19 Mayıs",
      "Acıbadem",
      "Bostancı",
      "Caddebostan",
      "Caferağa",
      "Eğitim",
      "Erenköy",
      "Fenerbahçe",
      "Feneryolu",
      "Fikirtepe",
      "Göztepe",
      "Hasanpaşa",
      "Koşuyolu",
      "Kozyatağı",
      "Merdivenköy",
      "Osmanağa",
      "Rasimpaşa",
      "Sahrayıcedit",
      "Suadiye",
      "Zühtüpaşa"
    ]
  },
  {
    "district": "Kağıthane",
    "neighborhoods": [
      "Çağlayan",
      "Çeliktepe",
      "Emniyet Evleri",
      "Gültepe",
      "Gürsel",
      "Hamidiye",
      "Harmantepe",
      "Hürriyet",
      "Mehmet Akif Ersoy",
      "Merkez",
      "Nurtepe",
      "Ortabayır",
      "Seyrantepe",
      "Sultan Selim",
      "Şirintepe",
      "Talatpaşa",
      "Telsizler",
      "Yahya Kemal",
      "Yeşilce"
    ]
  },
  {
    "district": "Kartal",
    "neighborhoods": [
      "Atalar",
      "Cevizli",
      "Cumhuriyet",
      "Çavuşoğlu",
      "Esentepe",
      "Gümüşpınar",
      "Hürriyet",
      "Karlıktepe",
      "Kordonboyu",
      "Orhantepe",
      "Orta",
      "Petrol İş",
      "Soğanlık Yeni",
      "Uğur Mumcu",
      "Yakacık Çarşı",
      "Yalı",
      "Yukarı",
      "Yunus"
    ]
  },
  {
    "district": "Küçükçekmece",
    "neighborhoods": [
      "Atakent",
      "Atatürk",
      "Beşyol",
      "Cennet",
      "Fatih",
      "Fevzi Çakmak",
      "Gültepe",
      "Halkalı Merkez",
      "İnönü",
      "İstasyon",
      "Kanarya",
      "Kartaltepe",
      "Kemalpaşa",
      "Mehmet Akif",
      "Söğütlü Çeşme",
      "Tevfikbey",
      "Yarımburgaz",
      "Yeni Mahalle",
      "Yeşilova"
    ]
  },
  {
    "district": "Maltepe",
    "neighborhoods": [
      "Altayçeşme",
      "Altıntepe",
      "Aydınevler",
      "Bağlarbaşı",
      "Başıbüyük",
      "Büyükbakkalköy",
      "Cevizli",
      "Çınar",
      "Esenkent",
      "Feyzullah",
      "Fındıklı",
      "Girne",
      "Gülensu",
      "Gülsuyu",
      "İdealtepe",
      "Küçükyalı Merkez",
      "Yalı",
      "Zümrütevler"
    ]
  },
  {
    "district": "Pendik",
    "neighborhoods": [
      "Ahmet Yesevi",
      "Bahçelievler",
      "Ballıca",
      "Batı",
      "Çamçeşme",
      "Çamlık",
      "Çınardere",
      "Doğu",
      "Dumlupınar",
      "Emirli",
      "Ertuğrul Gazi",
      "Esenler",
      "Esenyalı",
      "Fatih",
      "Fevzi Çakmak",
      "Göçbeyli",
      "Güllü Bağlar",
      "Güzelyalı",
      "Harmandere",
      "Kavakpınar",
      "Kaynarca",
      "Kurna",
      "Kurtdoğmuş",
      "Kurtköy",
      "Orhangazi",
      "Orta",
      "Ramazanoğlu",
      "Sapan Bağları",
      "Sülüntepe",
      "Şeyhli",
      "Velibaba",
      "Yayalar",
      "Yeni",
      "Yenişehir",
      "Yeşilbağlar"
    ]
  },
  {
    "district": "Sancaktepe",
    "neighborhoods": [
      "Abdurrahmangazi",
      "Akpınar",
      "Atatürk",
      "Emek",
      "Eyüp Sultan",
      "Fatih",
      "Hilal",
      "İnönü",
      "Kemal Türkler",
      "Meclis",
      "Merve",
      "Mevlana",
      "Osmangazi",
      "Paşaköy",
      "Safa",
      "Sarıgazi",
      "Veysel Karani",
      "Yenidoğan",
      "Yunus Emre"
    ]
  },
  {
    "district": "Sarıyer",
    "neighborhoods": [
      "Ayazağa",
      "Bahçeköy Kemer",
      "Bahçeköy Merkez",
      "Bahçeköy Yenimahalle",
      "Baltalimanı",
      "Büyükdere",
      "Cumhuriyet",
      "Çamlıtepe",
      "Çayırbaşı",
      "Darüşşafaka",
      "Demirciköy",
      "Emirgan",
      "Fatih Sultan Mehmet",
      "Ferahevler",
      "Garipçe",
      "Gümüşdere",
      "Huzur",
      "İstinye",
      "Kazım Karabekir Paşa",
      "Kısırkaya",
      "Kireçburnu",
      "Kocataş",
      "Kumköy (kilyos)",
      "Maden",
      "Maslak",
      "Pınar",
      "Poligon",
      "Ptt Evleri",
      "Reşitpaşa",
      "Rumeli Kavağı",
      "Rumelifeneri",
      "Sarıyer Merkez",
      "Sarıyer Yenimahalle",
      "Tarabya",
      "Uskumruköy",
      "Yeniköy",
      "Zekeriyaköy"
    ]
  },
  {
    "district": "Silivri",
    "neighborhoods": [
      "Akören",
      "Alibey",
      "Alipaşa",
      "Bekirli",
      "Beyciler",
      "Büyük Çavuşlu",
      "Büyük Kılıçlı",
      "Büyük Sinekli",
      "Çanta Sancaktepe",
      "Çayırdere",
      "Çeltik",
      "Danamandıra",
      "Değirmenköy Fevzipaşa",
      "Fatih",
      "Fener",
      "Gazitepe",
      "Gümüşyaka",
      "Kadıköy",
      "Kavaklı İstiklal",
      "Kurfallı",
      "Küçük Kılıçlı",
      "Küçük Sinekli",
      "Ortaköy",
      "Piri Mehmet Paşa",
      "Sayalar",
      "Selimpaşa",
      "Semizkumlar",
      "Seymen",
      "Yolçatı"
    ]
  },
  {
    "district": "Sultanbeyli",
    "neighborhoods": [
      "Abdurrahmangazi",
      "Adil",
      "Ahmet Yesevi",
      "Akşemsettin",
      "Battalgazi",
      "Fatih",
      "Hamidiye",
      "Hasanpaşa",
      "Mecidiye",
      "Mehmet Akif",
      "Mimar Sinan",
      "Necip Fazıl",
      "Orhangazi",
      "Turgut Reis",
      "Yavuz Selim"
    ]
  },
  {
    "district": "Sultangazi",
    "neighborhoods": [
      "50. Yıl",
      "75. Yıl",
      "Cebeci",
      "Cumhuriyet",
      "Esentepe",
      "Eski Habipler",
      "Gazi",
      "Habibler",
      "İsmetpaşa",
      "Malkoçoğlu",
      "Sultançiftliği",
      "Uğur Mumcu",
      "Yayla",
      "Yunus Emre",
      "Zübeyde Hanım"
    ]
  },
  {
    "district": "Şile",
    "neighborhoods": [
      "Ağaçdere",
      "Ağva Merkez",
      "Ahmetli",
      "Akçakese",
      "Alacalı",
      "Avcıkoru",
      "Balibey",
      "Bıçkıdere",
      "Bozgoca",
      "Bucaklı",
      "Çataklı",
      "Çavuş",
      "Çayırbaşı",
      "Çelebi",
      "Çengilli",
      "Darlık",
      "Değirmençayırı",
      "Doğancılı",
      "Erenler",
      "Esenceli",
      "Geredeli",
      "Göçe",
      "Gökmaşlı",
      "Göksu",
      "Hacıllı",
      "Hasanlı",
      "İmrendere",
      "İmrenli",
      "İsaköy",
      "Kabakoz",
      "Kadıköy",
      "Kalem",
      "Karabeyli",
      "Karacaköy",
      "Karakiraz",
      "Karamandere",
      "Kervansaray",
      "Kızılca",
      "Korucu",
      "Kömürlük",
      "Kumbaba",
      "Kurfallı",
      "Kurna",
      "Meşrutiyet",
      "Oruçoğlu",
      "Osmanköy",
      "Ovacık",
      "Sahilköy",
      "Satmazlı",
      "Sofular",
      "Soğullu",
      "Sortullu",
      "Şuayipli",
      "Teke",
      "Ulupelit",
      "Üvezli",
      "Yaka",
      "Yaylalı",
      "Yazımanayır",
      "Yeniköy",
      "Yeşilvadi"
    ]
  },
  {
    "district": "Şişli",
    "neighborhoods": [
      "19 Mayıs",
      "Bozkurt",
      "Cumhuriyet",
      "Duatepe",
      "Ergenekon",
      "Esentepe",
      "Eskişehir",
      "Feriköy",
      "Fulya",
      "Gülbahar",
      "Halide Edip Adıvar",
      "Halil Rıfat Paşa",
      "İzzet Paşa",
      "Kaptanpaşa",
      "Kuştepe",
      "Mahmut Şevket Paşa",
      "Mecidiyeköy",
      "Merkez",
      "Meşrutiyet",
      "Paşa",
      "Teşvikiye"
    ]
  },
  {
    "district": "Tuzla",
    "neighborhoods": [
      "Akfırat",
      "Anadolu",
      "Aydınlı",
      "Aydıntepe",
      "Cami",
      "Evliya Çelebi",
      "Fatih",
      "İçmeler",
      "İstasyon",
      "Mescit",
      "Mimar Sinan",
      "Orhanlı",
      "Orta",
      "Postane",
      "Şifa",
      "Tepeören",
      "Yayla"
    ]
  },
  {
    "district": "Ümraniye",
    "neighborhoods": [
      "Adem Yavuz",
      "Altınşehir",
      "Armağanevler",
      "Aşağı Dudullu",
      "Atakent",
      "Atatürk",
      "Cemil Meriç",
      "Çakmak",
      "Çamlık",
      "Dumlupınar",
      "Elmalıkent",
      "Esenevler",
      "Esenkent",
      "Esenşehir",
      "Fatih Sultan Mehmet",
      "Hekimbaşı",
      "Huzur",
      "Ihlamurkuyu",
      "İnkılap",
      "İstiklal",
      "Kazım Karabekir",
      "Madenler",
      "Mehmet Akif",
      "Namık Kemal",
      "Necip Fazıl",
      "Parseller",
      "Saray",
      "Site",
      "Şerifali",
      "Tantavi",
      "Tatlısu",
      "Tepeüstü",
      "Topağacı",
      "Yamanevler",
      "Yenişehir",
      "Yukarı Dudullu"
    ]
  },
  {
    "district": "Üsküdar",
    "neighborhoods": [
      "Acıbadem",
      "Ahmediye",
      "Altunizade",
      "Aziz Mahmut Hüdayi",
      "Barbaros",
      "Beylerbeyi",
      "Bulgurlu",
      "Burhaniye",
      "Cumhuriyet",
      "Çengelköy",
      "Ferah",
      "İcadiye",
      "Kandilli",
      "Kısıklı",
      "Kirazlıtepe",
      "Kuzguncuk",
      "Küçükçamlıca",
      "Küçüksu",
      "Mehmet Akif Ersoy",
      "Mimar Sinan",
      "Muratreis",
      "Salacak",
      "Selimiye",
      "Sultantepe",
      "Ünalan",
      "Valide-i Atik",
      "Yavuztürk",
      "Zeynep Kamil"
    ]
  },
  {
    "district": "Zeytinburnu",
    "neighborhoods": [
      "Beştelsiz",
      "Çırpıcı",
      "Gökalp",
      "Kazlıçeşme",
      "Maltepe",
      "Merkezefendi",
      "Nuripaşa",
      "Seyitnizam",
      "Sümer",
      "Telsiz",
      "Veliefendi",
      "Yenidoğan"
    ]
  }
] as const;
