export const districts = [
  { name: "Adalar", slug: "adalar-moto-kurye" },
  { name: "Arnavutkoy", slug: "arnavutkoy-moto-kurye" },
  { name: "Atasehir", slug: "atasehir-moto-kurye" },
  { name: "Avcilar", slug: "avcilar-moto-kurye" },
  { name: "Bagcilar", slug: "bagcilar-moto-kurye" },
  { name: "Bahcelievler", slug: "bahcelievler-moto-kurye" },
  { name: "Bakirkoy", slug: "bakirkoy-moto-kurye" },
  { name: "Basaksehir", slug: "basaksehir-moto-kurye" },
  { name: "Bayrampasa", slug: "bayrampasa-moto-kurye" },
  { name: "Besiktas", slug: "besiktas-moto-kurye" },
  { name: "Beykoz", slug: "beykoz-moto-kurye" },
  { name: "Beylikduzu", slug: "beylikduzu-moto-kurye" },
  { name: "Beyoglu", slug: "beyoglu-moto-kurye" },
  { name: "Buyukcekmece", slug: "buyukcekmece-moto-kurye" },
  { name: "Catalca", slug: "catalca-moto-kurye" },
  { name: "Cekmekoy", slug: "cekmekoy-moto-kurye" },
  { name: "Esenler", slug: "esenler-moto-kurye" },
  { name: "Esenyurt", slug: "esenyurt-moto-kurye" },
  { name: "Eyupsultan", slug: "eyupsultan-moto-kurye" },
  { name: "Fatih", slug: "fatih-moto-kurye" },
  { name: "Gaziosmanpasa", slug: "gaziosmanpasa-moto-kurye" },
  { name: "Gungoren", slug: "gungoren-moto-kurye" },
  { name: "Kadikoy", slug: "kadikoy-moto-kurye" },
  { name: "Kagithane", slug: "kagithane-moto-kurye" },
  { name: "Kartal", slug: "kartal-moto-kurye" },
  { name: "Kucukcekmece", slug: "kucukcekmece-moto-kurye" },
  { name: "Maltepe", slug: "maltepe-moto-kurye" },
  { name: "Pendik", slug: "pendik-moto-kurye" },
  { name: "Sancaktepe", slug: "sancaktepe-moto-kurye" },
  { name: "Sariyer", slug: "sariyer-moto-kurye" },
  { name: "Sile", slug: "sile-moto-kurye" },
  { name: "Silivri", slug: "silivri-moto-kurye" },
  { name: "Sisli", slug: "sisli-moto-kurye" },
  { name: "Sultanbeyli", slug: "sultanbeyli-moto-kurye" },
  { name: "Sultangazi", slug: "sultangazi-moto-kurye" },
  { name: "Tuzla", slug: "tuzla-moto-kurye" },
  { name: "Umraniye", slug: "umraniye-moto-kurye" },
  { name: "Uskudar", slug: "uskudar-moto-kurye" },
  { name: "Zeytinburnu", slug: "zeytinburnu-moto-kurye" }
];

const paragraphTemplates = [
  "{name} genelinde moto kurye hizmetinde en kritik konu, teslimatin sadece hizli degil ayni zamanda izlenebilir ve guvenilir olmasidir. Ekiplerimiz gonderiyi teslim alirken adres, kisi ve saat bilgilerini netlestirir; rota planini trafik yogunlugu, yol kapama olasiligi ve teslimat onceligine gore optimize eder. Bu sayede hem bireysel gonderilerde hem de kurumsal dagitimlarda sure kaybi yasamadan operasyonu tamamlariz.",
  "Acil evrak, sozlesme, numune urun veya e-ticaret paketi gibi zaman hassasiyeti yuksek gonderilerde {name} icindeki bolgesel deneyim fark yaratir. Suruculerimiz semt gecislerini, ana arter yogunlugunu ve alternatif guzergahlari bildigi icin teslimat surelerini daha isabetli yonetir. Musteriye teslimat asamalari boyunca bilgi verilmesi, surecin kontrol altinda ilerlemesini saglar.",
  "Gun icinde birden fazla noktaya dagitim gereken durumlarda planli toplu rota modeli kullaniriz. {name} icindeki ilk alim noktasindan son teslimat noktasina kadar tum duraklar operasyon panelinde sira ve oncelik bazli duzenlenir. Bu yaklasim hem yakit verimliligi hem de zaman yonetimi acisindan avantaj saglar; isletmelerin gonderi maliyetlerini kontrol etmesine yardim eder.",
  "Kurye hizmetinde hiz kadar iletisim kalitesi de onemlidir. {name} bolgesindeki operasyonlarimizda musteri temsilcisi, kurye ve alici arasinda net bir bilgi akisina odaklaniriz. Adres teyidi, teslimat notu, bina giris proseduru veya guvenlik birimi bilgilendirmesi gibi ayrintilar onceden tamamlandigi icin teslimat aninda gecikme olasiligi azalir.",
  "{name} icindeki firma teslimatlarinda fatura, irsaliye, teklif dosyasi ve imzali evrak transferleri duzenli takip ister. Bu nedenle her gonderide alinma saati, cikis noktasi, teslim alacak kisi ve dogrulama adimi standartlastirilir. Surecin sonunda teslimat kaydi olusturularak hem operasyon hem de muhasebe ekiplerinin kullanabilecegi net bir raporlama cikisi saglanir.",
  "Bireysel kullanicilar icin en cok tercih edilen senaryolardan biri, ayni gun icinde farkli semte ulasmasi gereken ozel gonderilerdir. {name} merkezli cikislarda aciliyet durumuna gore ekspres ya da planli teslimat secenekleri sunariz. Boylece gonderinin hem butceye uygun hem de zamaninda yerine ulasmasi mumkun olur.",
  "Hassas urun tasimaciliginda paketleme kadar surus disiplini de belirleyicidir. {name} rotalarinda kurye ekiplerimiz ani fren, keskin manevra ve dengesiz yukleme risklerini azaltacak sekilde egitilir. Ozellikle cam urun, elektronik parca veya numune kutusu tasimalarinda ek sabitleme ve koruyucu paket kontrolu uygulanir.",
  "Isletmeler icin surekli kurye ihtiyacinda aylik operasyon plani hazirlamak verimi artirir. {name} icin olusturulan duzenli dagitim takviminde gunluk alim saatleri, pik saat alternatifleri ve yogun gun destekleri tanimlanir. Bu model sayesinde isletmeler son dakika organizasyon yukunu azaltarak ana islerine odaklanabilir.",
  "Teslimat sureclerinde guven unsuru sadece hizli varisla sinirli degildir. {name} bolgesindeki operasyonlarimizda teslim edecek kisi bilgisi, telefon dogrulamasi ve gerekirse imza kaydi kullanilir. Boylesi bir dogrulama zinciri, ozellikle hukuki evrak veya yuksek degerli urun gonderilerinde hatali teslim riskini minimuma indirir.",
  "Yogun hava kosullarinda dahi hizmetin surdurulebilir olmasi icin alternatif planlama yapisi kuruyoruz. {name} icinde yagisli gunlerde guvenli surus temposu korunurken, toplam sureyi dengelemek icin rota sirasi yeniden optimize edilir. Musteri tarafinda beklenti yonetimi seffaf bir sekilde yapildigi icin operasyon kalitesi korunur.",
  "Ayni gun teslimat hizmetinde dakiklik, dogru bilgilendirme ve esnek rota yonetimi birlikte calisir. {name} icindeki dagitimlarda bu uc unsuru operasyon standartlarina bagliyoruz. Her teslimat sonunda elde edilen veriler, bir sonraki dagitim planinin daha da iyilesmesini saglayan geri bildirim havuzuna eklenir.",
  "Kurumsal markalar acisindan tutarli hizmet kalitesi en az teslimat hizi kadar onemlidir. {name} operasyonlarinda belirli SLA hedefleri ile calisiyor, gecikme riski olusan durumlarda proaktif bildirim mekanizmasi devreye aliyoruz. Bu sayede markalar kendi musterilerine daha guvenli bir deneyim sunabiliyor.",
  "Trafik yogunlugunun arttigi saatlerde ilk adim, cikis ve varis noktalarinin alternatif yol seceneklerini karsilastirmaktir. {name} icindeki teslimatlarda ana arterin tikandigi anlarda baglanti yollari ve semt gecisleri devreye alinarak toplam sure korunur. Planlama asamasinda verilen dogru adres detayi bu avantajin temelini olusturur.",
  "Evrak ve hassas urun transferlerinde teslimat oncesi kontrol listesi kullaniriz. {name} operasyonunda gonderi turu, teslim alacak kisi, kat bilgisi, guvenlik gecis notu ve irtibat telefonu dogrulanir. Bu kontrol listesi, sahada yasanabilecek yanlis adrese gitme veya eksik bilgi kaynakli gecikmeleri belirgin sekilde azaltir.",
  "Maliyet yonetiminde tek kriter en ucuz secenek degildir; teslimatin hedef saate ulasmasi da ayni derecede kritiktir. {name} icindeki acil gonderilerde ekspres model, standart gonderilerde planli rota modeli kullanilarak performans ve butce dengesi saglanir. Musteri ihtiyacina gore dogru model secildiginde verimlilik artar.",
  "Duzenli kurye kullanan firmalar icin haftalik ve aylik performans takibi stratejik fayda saglar. {name} bolgesine yonelik raporlarda teslimat adedi, zamaninda varis orani ve rota verimliligi gibi metrikler degerlendirilir. Bu veriler, sirketin lojistik kararlarini somut veriye dayali sekilde gelistirmesine yardim eder.",
  "Musteri bilgilendirmesinin acik ve zamaninda yapilmasi, kurye hizmet kalitesini dogrudan etkiler. {name} icindeki her operasyonda alim onayi, yolda bilgisi ve teslimat bildirimi adimlarini standart hale getiririz. Bu surec hem gonderici hem alici tarafinda guven olusturur.",
  "Teslimatin son asamasinda isim dogrulamasi, teslim saati kaydi ve gerekli durumlarda imza teyidi alinir. {name} operasyonlarinda bu final kontrol adimi hizmetin tamamlayici parcasidir. Boylece teslimat tamamlandiginda surecin butun asamalari dokumante edilmis olur ve olasi itirazlar kolayca yonetilir.",
  "Yuksek adetli dagitim gunlerinde kapasiteyi dogru yonetmek icin vardiya bazli kurye planlamasi uyguluyoruz. {name} icinde sabah, ogle ve aksam yogunluklari farkli oldugundan teslimat turleri saat dilimine gore ayrilir. Bu yontem, hem sahadaki bekleme suresini azaltir hem de musterinin planlanan zamanda hizmet almasini kolaylastirir.",
  "Adres dogrulugu teslimat hizinin temel unsurudur. {name} bolgesinde bina numarasi, giris kapisi, is yeri kat bilgisi ve alici telefonunun guncel olmasi rota performansini dogrudan iyilestirir. Operasyon oncesinde yapilan kisa bilgi teyidi, sahada ortaya cikabilecek gereksiz tur sayisini azaltir.",
  "E-ticaret operasyonlarinda iade gonderileri de en az cikis teslimatlari kadar kritik yonetim ister. {name} icindeki iade alimlarinda urun kontrolu, paket durumu ve teslim kaydi ayni anda tamamlanir. Bu sayede satici tarafi stok ve lojistik akisina daha hizli hakim olur, musteri memnuniyeti korunur.",
  "Hizmet kalitesinin devamli gelismesi icin operasyon sonu geri bildirimlerini duzenli analiz ederiz. {name} teslimatlarinda alinan yorumlar, gecikme nedenleri ve rota performans notlari aylik olarak degerlendirilir. Elde edilen icgoru, bir sonraki donemde daha hizli ve daha tutarli teslimat standartlari olusturmamiza yardim eder.",
  "Ozellikle finans, hukuk, saglik ve perakende sektorlerinde belge akisinin aksamamasi buyuk onem tasir. {name} icindeki sektor odakli kurye planlamasinda gizlilik, zamanlama ve teslim teyidi protokolleri birlikte ele alinir. Bu disiplinli yaklasim, kritik is sureclerinin kesintisiz sekilde ilerlemesini destekler.",
  "Sehir ici lojistikte guvenilir partner secimi, operasyonel riskleri azaltan stratejik bir karardir. {name} bolgesinde sundugumuz moto kurye hizmeti; hiz, izlenebilirlik, iletisim ve teslim dogrulamasi gibi temel basliklari ayni standartta birlestirir. Bu butuncul yapi sayesinde hem bireysel hem kurumsal gonderilerde sureklilik saglanir."
];

export function buildDistrictContent(district) {
  const longParagraphs = paragraphTemplates.map((template) => template.replaceAll("{name}", district.name));
  return {
    ...district,
    regionLabel: `${district.name} ve Cevresi`,
    shortText: `${district.name} icinde acil moto kurye, ayni gun teslimat ve planli dagitim cozumleri.`,
    intro: `${district.name} bolgesinde zamanla yarisan teslimatlariniz icin hizli cikis, net takip ve guvenli ulasim odakli moto kurye hizmeti sunuyoruz. Evrak, paket ve kurumsal dagitim ihtiyacinizda 7/24 destek veriyoruz.`,
    longParagraphs,
    faqItems: [
      `${district.name} icinde ortalama teslimat suresi ne kadar?`,
      "Acil gonderilerde ekspres secenek var mi?",
      "Kurumsal firmalara duzenli kurye anlasmasi yapiyor musunuz?",
      "Evrak teslimatlarinda imza veya teslim kaydi sagliyor musunuz?",
      "WhatsApp uzerinden anlik kurye cagirma mumkun mu?"
    ],
    outro: `${district.name} icinde guvenilir bir moto kurye partneri ariyorsaniz 05303219004 numarasini arayabilir veya WhatsApp uzerinden aninda talep olusturabilirsiniz. Hedefimiz, her teslimati planli, hizli ve sorunsuz bicimde tamamlamaktir.`
  };
}
