export const blogKeywords = [
  "istanbul moto kurye",
  "acil kurye",
  "hizli kurye",
  "ayni gun teslimat",
  "ekspres kurye",
  "gece kurye",
  "vip kurye",
  "istanbul acil teslimat",
  "kurumsal kurye",
  "evrak tasima",
  "paket teslimati",
  "sehir ici kurye",
  "moto kurye hizmeti",
  "istanbul ekspres kurye",
  "7 24 kurye",
  "anadolu yakasi kurye",
  "avrupa yakasi kurye",
  "hizli evrak teslimi",
  "ofisten ofise kurye",
  "medikal kurye",
  "e ticaret kurye",
  "numune tasima",
  "tek adrese teslimat",
  "cok adresli dagitim",
  "gece teslimat hizmeti",
  "son dakika kurye",
  "kurumsal sevkiyat",
  "belge gonderimi",
  "istanbul dagitim hizmeti",
  "rezidans teslimati",
  "plaza kurye",
  "bireysel kurye hizmeti",
  "kurye cagirma",
  "hastane kurye",
  "hukuk burosu kurye",
  "teknik servis kurye",
  "iade degisim kuryesi",
  "istanbul paket dagitimi",
  "kurye organizasyonu",
  "istanbul teslimat rehberi",
  "besiktas kurye",
  "kadikoy kurye",
  "sisli kurye",
  "atasehir kurye",
  "maltepe kurye",
  "umraniye kurye",
  "kartal kurye",
  "bakirkoy kurye",
  "sariyer kurye",
  "levent kurye",
  "maslak kurye",
  "pendik kurye",
  "istanbul avrupa yakasi acil kurye",
  "istanbul anadolu yakasi acil kurye",
  "motor kurye istanbul",
  "kurye ucreti istanbul",
  "istanbul kurye fiyatlari",
  "acil kurye fiyat",
  "acil evrak gonderimi",
  "resmi evrak teslimat",
  "mahkeme evrak kuryesi",
  "noter evrak teslimi",
  "sozlesme teslimi kurye",
  "laboratuvar numune tasima",
  "saglik sektoru kurye",
  "ilac teslimat hizmeti",
  "klinik numune kuryesi",
  "e ticaret son mil teslimat",
  "e ticaret iade kurye",
  "online siparis teslimati istanbul",
  "kargo yerine kurye",
  "kurye mi kargo mu",
  "ajans kurye hizmeti",
  "matbaa urun dagitimi",
  "tekstil sektor kurye",
  "numune gonderim hizmeti",
  "urun ornegi teslimat",
  "hediye gonderimi istanbul",
  "ozel esya tasima istanbul",
  "elektronik cihaz kurye",
  "bilgisayar parcasi gonderimi",
  "yedek parca kurye istanbul",
  "bakim parcasi teslimi",
  "gunluk kurye aboneligi",
  "kurumsal kurye sozlesmesi",
  "aylik kurye paketi istanbul",
  "duzenli teslimat hizmeti",
  "stok transfer kurye",
  "depo teslimat kurye",
  "fabrika kurye hizmeti",
  "ofis malzemesi teslimati",
  "kurye takip sistemi",
  "teslimat onay bildirimi",
  "kurye whatsapp siparis",
  "whatsapp kurye istanbul",
  "gece yarisi teslimat",
  "sabah erken teslimat",
  "hafta sonu kurye istanbul",
  "pazar gunu kurye",
  "resmi tatil kurye hizmeti",
  "bayram kurye istanbul",
] as const;

export const BLOG_SCHEDULE_TIMES = ["10:00", "16:30"] as const;